#!/usr/bin/env node

const vPrefix = process.argv[2] + '-';
const tag = process.argv[3];

if(!tag.startsWith(vPrefix)) throw new Error(`Tag information looks wrong for module ${tag}: ${process.argv[2]}`);

const v = tag.substring(vPrefix.length);

const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json').toString());

if(pkg.version !== v) {
  pkg.version = v;
  fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
}
